<?php
$conflicted_pages = array(
	"jobcareer" => array(
		"About Us",
		"Alphabatic Listing",
		"Candidate Dashboard",
		"Candidate Simple Grid View",
		"Candidates List with Filterable",
		"Candidates List with Map",
		"Contact Us",
		"CV Packages",
		"Employer Account",
		"Employer Grid",
		"Employer List View",
		"Employer Listing 3Columns",
		"Employer View With Filter",
		"Frequently Asked Questions",
		"Home",
		"Jobs Classic view",
		"Jobs Detail List",
		"Jobs Grid View",
		"Jobs List Modern",
		"Jobs Modern List",
		"Jobs Packages",
		"Jobs Simple List View",
		"News Grid",
		"News Large",
		"News Medium",
		"Packages",
		"Product",
		"Register",
		"Search Result Page",
		"Terms and Policies",
	),
	"jobcareer-rtl" => array(
		"اخبار شبکه",
		"الفبایی فهرست",
		"امکانات",
		"بسته",
		"بسته رزومه",
		"تماس با ما",
		"تماس با ما 2",
		"تولید - محصول",
		"ثبت نام",
		"جابز شبکه نمایش",
		"جابز فهرست جزئیات",
		"جابز فهرست ساده مشخصات",
		"جابز فهرست مدرن",
		"جابز فهرست مدرن",
		"حساب کارفرما",
		"خانه",
		"داشبورد نامزد",
		"دربارهی ما",
		"سوالات متداول",
		"شبکه کارفرما",
		"شغل بسته",
		"قوانین و مقررات و سیاست",
		"کارفرما فهرست نمایش",
		"کارفرما لیست 3 ستون ها",
		"کارفرما نمایش با فیلتر",
		"مشخصات شغل کلاسیک",
		"نامزد ساده شبکه نمایش",
		"نامزدهای با پالایش",
		"نامزدهای با نقشه",
		"نتیجه جستجو صفحه",
	),
	"nextjob" => array(
		"About Us",
		"Alphabatic Listing",
		"Candidate Dashboard",
		"Candidate Simple Grid View",
		"Candidates List with Filterable",
		"Contact Us",
		"CV Packages",
		"Employer Account",
		"Employer Grid",
		"Employer List View",
		"Employer Listing 3Columns",
		"Employer View With Filter",
		"Frequently Asked Questions",
		"Home",
		"Jobs Classic view",
		"Jobs Detail List",
		"Jobs Grid View",
		"Jobs List Modern",
		"Jobs Modern List",
		"Jobs Packages",
		"Jobs Simple List View",
		"News Grid",
		"News Large",
		"News Medium",
		"Packages",
		"Product",
		"Register",
		"Search Result Page",
		"Terms and Policies",
	),
	"recruiter" => array(
		"About Us",
		"Candidate Dashboard",
		"Clients",
		"Contact Us",
		"Employer Account",
		"Find Candidates",
		"Find Jobs",
		"Jobs List Modern",
		"Jobs Simple List View",
		"News",
		"Recruiter Home",
		"Register",
		"Search Result Page",
		"Terms and Policies",
	),
	"jobstack" => array(
		"About Us",
		"Alphabatic Listing",
		"Candidate Dashboard",
		"Candidate Simple Grid View",
		"Candidates List with Filterable",
		"Candidates List with Map",
		"Contact Us",
		"CV Packages",
		"Employer Account",
		"Employer Grid",
		"Employer List View",
		"Employer Listing 3Columns",
		"Employer View With Filter",
		"Frequently Asked Questions",
		"Home",
		"Jobs Classic view",
		"Jobs Detail List",
		"Jobs Grid View",
		"Jobs List Modern",
		"Jobs Modern List",
		"Jobs Packages",
		"Jobs Simple List View",
		"News Grid",
		"News Large",
		"News Medium",
		"Packages",
		"Product",
		"Register",
		"Search Result Page",
		"Terms and Policies",
	),
	"jobdoor" => array(
		"About Us",
		"Alphabatic Listing",
		"Candidate Dashboard",
		"Candidates List with Map",
		"Contact Us",
		"Employer Account",
		"Jobdoor Home",
		"Jobs Grid View",
		"Jobs Packages",
	)
);